### ISSUE TITLE
任务前面的图标是否改成todo的这个图标

### ISSUE THREAD

**Issue by 397334469** [syh19/siyuan-plugin-task-list#27]
原来的：
![image](https://github.com/syh19/siyuan-plugin-task-list/assets/51410244/fe29390c-c86f-4c0f-982d-e676b1195e88)
建议的：
![image](https://github.com/syh19/siyuan-plugin-task-list/assets/51410244/b855a2ec-997c-485d-a896-dd423bc1fe7b)

**Comment by syh19** [comment]
您是想要在插件界面直接通过勾选来**完成**或者**取消完成**任务吗？

**Comment by 397334469** [comment]
> 您是想要在插件界面直接通过勾选来**完成**或者**取消完成**任务吗？

不是，是现在红色时钟有点太显眼了，想换成默认的那种图标

**Comment by 397334469** [comment]
能否帮忙提供一个参考代码，感谢

**Comment by syh19** [comment]
@397334469 
您可以参考下面的`CSS`代码片段：
```css
/** 任务列表插件CSS代码片段 */

/** 未完成任务图标颜色 */
#siyuan-plugin-task-list .icon-label-wrap svg.icon-todo {
  color: pink;
}

/** 完成任务图标颜色 */
#siyuan-plugin-task-list .icon-label-wrap svg.icon.icon-done {
  color: green;
}

/** 日历视图上选定日期的背景色 */
#siyuan-plugin-task-list .vc-container .vc-highlight-content-solid {
  background-color: pink !important;
}
```
